### ISSUE TITLE
[BUG] Prediction fails with an exception

### ISSUE THREAD

**Issue by hubbardp** [CAREamics/careamics-ui#24]
## Describe the bug
After training Noise2Void on one image, I tried to run prediction using the "From Disk" tab.  I chose a folder containing another image and pressed the "Predict" button. Napari immediately showed "Sample 1/inf" in the user interface, printed a long exception message in the shell from which I launched the application, and stopped doing prediction.

## To Reproduce

>mamba create -n napari-careamics python=3.10
>mamba activate napari-careamics
>mamba install -c conda-forge napari pyqt
>mamba install pytorch torchvision pytorch-cuda=11.8 -c pytorch -c nvidia
>python -m pip install careamics-napari "napari[all]"
>napari

Train on 1 image
Predict on a folder containing 1 image
Exception in the shell:

C:/Users/hubbardp/Documents/careamics/n2v-test-01/testing
13:06:05 : INFO : Thread-96 (_predict) : LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Predicting DataLoader 0: |                                                                       | 0/? [00:00<?, ?it/s]---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~\.conda\envs\napari-careamics\lib\site-packages\psygnal\_signal.py:1279, in SignalInstance._run_emit_loop(self=<_DataclassFieldSignalInstance 'max_samples' on ...up 'PredictionStatusSignalGroup' with 3 signals>>, args=(inf, -1))
   1278     with Signal._emitting(self):
-> 1279         self._run_emit_loop_inner()
        self = <_DataclassFieldSignalInstance 'max_samples' on <SignalGroup 'PredictionStatusSignalGroup' with 3 signals>>
        self._run_emit_loop_inner = <bound method SignalInstance._run_emit_loop_immediate of <_DataclassFieldSignalInstance 'max_samples' on <SignalGroup 'PredictionStatusSignalGroup' with 3 signals>>>
   1280 except RecursionError as e:

File ~\.conda\envs\napari-careamics\lib\site-packages\psygnal\_signal.py:1308, in SignalInstance._run_emit_loop_immediate(self=<_DataclassFieldSignalInstance 'max_samples' on ...up 'PredictionStatusSignalGroup' with 3 signals>>)
   1307 for caller in self._slots:
-> 1308     caller.cb(args)
        args = (inf, -1)
        caller = <WeakMethod on careamics_napari.widgets.prediction_widget.PredictionWidget._update_max_sample>

File ~\.conda\envs\napari-careamics\lib\site-packages\psygnal\_weak_callback.py:454, in WeakMethod.cb(self=<WeakMethod on careamics_napari.widgets.prediction_widget.PredictionWidget._update_max_sample>, args=(inf,))
    453     args = args[: self._max_args]
--> 454 func(obj, *self._args, *args, **self._kwargs)
        obj = <careamics_napari.widgets.prediction_widget.PredictionWidget object at 0x0000023363A88430>
        func = <function PredictionWidget._update_max_sample at 0x0000023362E3B010>
        args = (inf,)
        self = <WeakMethod on careamics_napari.widgets.prediction_widget.PredictionWidget._update_max_sample>
        self._args = ()
        self._kwargs = {}

File ~\.conda\envs\napari-careamics\lib\site-packages\careamics_napari\widgets\prediction_widget.py:240, in PredictionWidget._update_max_sample(self=<careamics_napari.widgets.prediction_widget.PredictionWidget object>, max_sample=inf)
    233 """Update the maximum value of the progress bar.
    234
    235 Parameters
   (...)
    238     The new maximum value of the progress bar.
    239 """
--> 240 self.pb_prediction.setMaximum(max_sample)
        max_sample = inf
        self.pb_prediction = <PyQt5.QtWidgets.QProgressBar object at 0x0000023363A89EA0>
        self = <careamics_napari.widgets.prediction_widget.PredictionWidget object at 0x0000023363A88430>

TypeError: setMaximum(self, maximum: int): argument 1 has unexpected type 'float'

The above exception was the direct cause of the following exception:

EmitLoopError                             Traceback (most recent call last)
File ~\.conda\envs\napari-careamics\lib\site-packages\careamics_napari\training_plugin.py:364, in TrainPlugin._update_from_prediction(self=<careamics_napari.training_plugin.TrainPlugin object>, update=PredictionUpdate(type=<PredictionUpdateType.MAX_SAMPLES: 'max_samples'>, value=inf))
    362         self.viewer.add_image(samples, name="Prediction")
    363 else:
--> 364     self.pred_status.update(update)
        update = PredictionUpdate(type=<PredictionUpdateType.MAX_SAMPLES: 'max_samples'>, value=inf)
        self.pred_status = PredictionStatus(max_samples=inf, sample_idx=-1, state=<PredictionState.PREDICTING: 1>)
        self = <careamics_napari.training_plugin.TrainPlugin object at 0x0000023342C70550>

File ~\.conda\envs\napari-careamics\lib\site-packages\careamics_napari\signals\prediction_status.py:119, in PredictionStatus.update(self=PredictionStatus(max_samples=inf, sample_idx=-1, state=<PredictionState.PREDICTING: 1>), new_update=PredictionUpdate(type=<PredictionUpdateType.MAX_SAMPLES: 'max_samples'>, value=inf))
    105 """Update the status with the new values.
    106
    107 Exceptions, debugging messages and samples are ignored.
   (...)
    112     New update to apply.
    113 """
    114 if (
    115     new_update.type != PredictionUpdateType.EXCEPTION
    116     and new_update.type != PredictionUpdateType.DEBUG
    117     and new_update.type != PredictionUpdateType.SAMPLE
    118 ):
--> 119     setattr(self, new_update.type.value, new_update.value)
        new_update.type = <PredictionUpdateType.MAX_SAMPLES: 'max_samples'>
        self = PredictionStatus(max_samples=inf, sample_idx=-1, state=<PredictionState.PREDICTING: 1>)
        new_update.value = inf
        new_update = PredictionUpdate(type=<PredictionUpdateType.MAX_SAMPLES: 'max_samples'>, value=inf)

File ~\.conda\envs\napari-careamics\lib\site-packages\psygnal\_group_descriptor.py:401, in evented_setattr.<locals>._inner.<locals>._setattr_and_emit_(self=PredictionStatus(max_samples=inf, sample_idx=-1, state=<PredictionState.PREDICTING: 1>), name='max_samples', value=inf)
    398 if signal is None or len(signal) < 1:
    399     return super_setattr(self, name, value)
--> 401 with _changes_emitted(self, name, signal):
        signal = <_DataclassFieldSignalInstance 'max_samples' on <SignalGroup 'PredictionStatusSignalGroup' with 3 signals>>
        name = 'max_samples'
        self = PredictionStatus(max_samples=inf, sample_idx=-1, state=<PredictionState.PREDICTING: 1>)
    402     super_setattr(self, name, value)

File ~\.conda\envs\napari-careamics\lib\site-packages\psygnal\_group_descriptor.py:318, in _changes_emitted.__exit__(self=<psygnal._group_descriptor._changes_emitted object>, *args=(None, None, None))
    316 new: Any = getattr(self.obj, self.field, _NULL)
    317 if not _check_field_equality(type(self.obj), self.field, self._prev, new):
--> 318     self.signal.emit(new, self._prev)
        new = inf
        self = <psygnal._group_descriptor._changes_emitted object at 0x0000023333CD5390>
        self._prev = -1
        self.signal = <_DataclassFieldSignalInstance 'max_samples' on <SignalGroup 'PredictionStatusSignalGroup' with 3 signals>>

File ~\.conda\envs\napari-careamics\lib\site-packages\psygnal\_signal.py:1201, in SignalInstance.emit(self=<_DataclassFieldSignalInstance 'max_samples' on ...up 'PredictionStatusSignalGroup' with 3 signals>>, check_nargs=False, check_types=False, *args=(inf, -1))
   1197     from ._group import EmissionInfo
   1199     SignalInstance._debug_hook(EmissionInfo(self, args))
-> 1201 self._run_emit_loop(args)
        self = <_DataclassFieldSignalInstance 'max_samples' on <SignalGroup 'PredictionStatusSignalGroup' with 3 signals>>
        args = (inf, -1)

File ~\.conda\envs\napari-careamics\lib\site-packages\psygnal\_signal.py:1296, in SignalInstance._run_emit_loop(self=<_DataclassFieldSignalInstance 'max_samples' on ...up 'PredictionStatusSignalGroup' with 3 signals>>, args=(inf, -1))
   1288     loop_err = EmitLoopError(
   1289         exc=cb_err,
   1290         signal=self,
   (...)
   1293         emit_queue=self._emit_queue,
   1294     ).with_traceback(cb_err.__traceback__)
   1295     # this comment will show up in the traceback
-> 1296     raise loop_err from cb_err  # emit() call ABOVE || callback error BELOW
        loop_err = EmitLoopError("\n\nWhile emitting signal 'psygnal._group_descriptor.PredictionStatusSignalGroup.max_samples', an error occurred in a callback:\n\n  TypeError: setMaximum(self, maximum: int): argument 1 has unexpected type 'float'\n  ---------------------------------------------------------------------------------\n\n  SIGNAL EMISSION: \n    C:\\Users\\hubbardp\\.conda\\envs\\napari-careamics\\lib\\site-packages\\careamics_napari\\training_plugin.py:364 in _update_from_prediction\n      self.pred_status.update(update)\n    C:\\Users\\hubbardp\\.conda\\envs\\napari-careamics\\lib\\site-packages\\careamics_napari\\signals\\prediction_status.py:119 in update\n      setattr(self, new_update.type.value, new_update.value)  # <-- SIGNAL WAS EMITTED HERE\n    C:\\Users\\hubbardp\\.conda\\envs\\napari-careamics\\lib\\site-packages\\careamics_napari\\widgets\\prediction_widget.py:240 in _update_max_sample\n      self.pb_prediction.setMaximum(max_sample)  # <-- ERROR OCCURRED HERE \n\n      Local variables:\n          max_sample = inf")
   1297 finally:
   1298     self._recursion_depth -= 1

File ~\.conda\envs\napari-careamics\lib\site-packages\psygnal\_signal.py:1279, in SignalInstance._run_emit_loop(self=<_DataclassFieldSignalInstance 'max_samples' on ...up 'PredictionStatusSignalGroup' with 3 signals>>, args=(inf, -1))
   1275     self._max_recursion_depth = max(
   1276         self._max_recursion_depth, self._recursion_depth
   1277     )
   1278     with Signal._emitting(self):
-> 1279         self._run_emit_loop_inner()
        self = <_DataclassFieldSignalInstance 'max_samples' on <SignalGroup 'PredictionStatusSignalGroup' with 3 signals>>
        self._run_emit_loop_inner = <bound method SignalInstance._run_emit_loop_immediate of <_DataclassFieldSignalInstance 'max_samples' on <SignalGroup 'PredictionStatusSignalGroup' with 3 signals>>>
   1280 except RecursionError as e:
   1281     raise RecursionError(
   1282         f"RecursionError when "
   1283         f"emitting signal {self.name!r} with args {args}"
   1284     ) from e

File ~\.conda\envs\napari-careamics\lib\site-packages\psygnal\_signal.py:1308, in SignalInstance._run_emit_loop_immediate(self=<_DataclassFieldSignalInstance 'max_samples' on ...up 'PredictionStatusSignalGroup' with 3 signals>>)
   1306 args = self._emit_queue.popleft()
   1307 for caller in self._slots:
-> 1308     caller.cb(args)
        args = (inf, -1)
        caller = <WeakMethod on careamics_napari.widgets.prediction_widget.PredictionWidget._update_max_sample>

File ~\.conda\envs\napari-careamics\lib\site-packages\psygnal\_weak_callback.py:454, in WeakMethod.cb(self=<WeakMethod on careamics_napari.widgets.prediction_widget.PredictionWidget._update_max_sample>, args=(inf,))
    452 if self._max_args is not None:
    453     args = args[: self._max_args]
--> 454 func(obj, *self._args, *args, **self._kwargs)
        obj = <careamics_napari.widgets.prediction_widget.PredictionWidget object at 0x0000023363A88430>
        func = <function PredictionWidget._update_max_sample at 0x0000023362E3B010>
        args = (inf,)
        self = <WeakMethod on careamics_napari.widgets.prediction_widget.PredictionWidget._update_max_sample>
        self._args = ()
        self._kwargs = {}

File ~\.conda\envs\napari-careamics\lib\site-packages\careamics_napari\widgets\prediction_widget.py:240, in PredictionWidget._update_max_sample(self=<careamics_napari.widgets.prediction_widget.PredictionWidget object>, max_sample=inf)
    232 def _update_max_sample(self: Self, max_sample: int) -> None:
    233     """Update the maximum value of the progress bar.
    234
    235     Parameters
   (...)
    238         The new maximum value of the progress bar.
    239     """
--> 240     self.pb_prediction.setMaximum(max_sample)
        max_sample = inf
        self.pb_prediction = <PyQt5.QtWidgets.QProgressBar object at 0x0000023363A89EA0>
        self = <careamics_napari.widgets.prediction_widget.PredictionWidget object at 0x0000023363A88430>

EmitLoopError:

While emitting signal 'psygnal._group_descriptor.PredictionStatusSignalGroup.max_samples', an error occurred in a callback:

  TypeError: setMaximum(self, maximum: int): argument 1 has unexpected type 'float'

  SIGNAL EMISSION:
    C:\Users\hubbardp\.conda\envs\napari-careamics\lib\site-packages\careamics_napari\training_plugin.py:364 in _update_from_prediction
      self.pred_status.update(update)
    C:\Users\hubbardp\.conda\envs\napari-careamics\lib\site-packages\careamics_napari\signals\prediction_status.py:119 in update
      setattr(self, new_update.type.value, new_update.value)  # <-- SIGNAL WAS EMITTED HERE
    C:\Users\hubbardp\.conda\envs\napari-careamics\lib\site-packages\careamics_napari\widgets\prediction_widget.py:240 in _update_max_sample
      self.pb_prediction.setMaximum(max_sample)  # <-- ERROR OCCURRED HERE

      Local variables:
          max_sample = inf
Predicting DataLoader 0: |                                                               | 1/? [00:01<00:00,  0.90it/s]

## System
> - OS: Microsoft Windows 11 Enterprise 10.0.22631 Build 22631
> - Python version 3.10.18
> - PyTorch version 2.3.1  py3.10_cuda11.8_cudnn8_0
> - PyTorch lightning version 2.5.0
> - CAREamics version 0.0.12

### Environment
```yaml
name: napari-careamics
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _libavif_api=1.3.0=h57928b3_0
  - _openmp_mutex=4.5=2_gnu
  - alabaster=1.0.0=pyhd8ed1ab_1
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - aom=3.9.1=he0c23c2_0
  - app-model=0.3.0=pyhd8ed1ab_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - asciitree=0.3.3=py_2
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - blas=1.0=mkl
  - blosc=1.21.6=hfd34d9b_1
  - brotli-python=1.1.0=py310h9e98ed7_3
  - bzip2=1.0.8=h2466b09_7
  - c-blosc2=2.18.0=h9e57077_0
  - ca-certificates=2025.6.15=h4c7d964_0
  - cachey=0.2.1=pyh9f0ad1d_0
  - certifi=2025.6.15=pyhd8ed1ab_0
  - cffi=1.17.1=py310ha8f682b_0
  - charls=2.4.2=h1537add_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - click=8.2.1=pyh7428d3b_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - cpython=3.10.18=py310hd8ed1ab_0
  - cuda-cccl=12.9.27=0
  - cuda-cccl_win-64=12.9.27=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-profiler-api=12.9.79=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.9=3
  - cytoolz=1.0.1=py310ha8f682b_0
  - dask-core=2025.5.1=pyhd8ed1ab_0
  - dav1d=1.2.1=hcfcfb64_0
  - debugpy=1.8.14=py310h9e98ed7_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - docstring_parser=0.16=pyhd8ed1ab_0
  - docutils=0.21.2=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - fasteners=0.19=pyhd8ed1ab_1
  - filelock=3.18.0=pyhd8ed1ab_0
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - freetype=2.13.3=h57928b3_1
  - freetype-py=2.5.1=pyhd8ed1ab_1
  - fsspec=2025.5.1=pyhd8ed1ab_0
  - giflib=5.2.2=h64bf75a_0
  - glib=2.84.2=he8f994d_0
  - glib-tools=2.84.2=h4394cf3_0
  - gst-plugins-base=1.24.11=h3fe0a9e_0
  - gstreamer=1.24.11=h233a61a_0
  - h2=4.2.0=pyhd8ed1ab_0
  - heapdict=1.0.1=pyhd8ed1ab_2
  - hpack=4.1.0=pyhd8ed1ab_0
  - hsluv=5.0.4=pyhd8ed1ab_2
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.10=pyhd8ed1ab_1
  - imagecodecs=2025.3.30=py310h7617850_1
  - imageio=2.37.0=pyhfb79c49_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - in-n-out=0.2.1=pyhd8ed1ab_1
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.37.0=pyha7b4d00_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jsonschema=4.24.0=pyhd8ed1ab_0
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh5737063_0
  - jxrlib=1.1=hcfcfb64_3
  - kiwisolver=1.4.7=py310hc19bc0b_0
  - krb5=1.21.3=hdf4eb48_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libaec=1.1.4=h20038f6_0
  - libavif16=1.3.0=hf2698fe_0
  - libblas=3.9.0=12_win64_mkl
  - libbrotlicommon=1.1.0=h2466b09_3
  - libbrotlidec=1.1.0=h2466b09_3
  - libbrotlienc=1.1.0=h2466b09_3
  - libcblas=3.9.0=12_win64_mkl
  - libclang13=20.1.7=default_h6e92b77_0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.10.19=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.24=h76ddb4d_0
  - libexpat=2.7.0=he0c23c2_0
  - libffi=3.4.6=h537db12_1
  - libfreetype=2.13.3=h57928b3_1
  - libfreetype6=2.13.3=h0b5ce68_1
  - libgcc=15.1.0=h1383e82_2
  - libglib=2.84.2=hbc94333_0
  - libgomp=15.1.0=h1383e82_2
  - libhwloc=2.11.2=default_ha69328c_1001
  - libhwy=1.2.0=h1d1702c_0
  - libiconv=1.18=h135ad9c_1
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.0=h2466b09_0
  - libjxl=0.11.1=ha161b08_2
  - liblapack=3.9.0=12_win64_mkl
  - liblzma=5.8.1=h2466b09_2
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libogg=1.3.5=h2466b09_1
  - libpng=1.6.49=h7a4582a_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.50.1=h67fdade_0
  - libtiff=4.7.0=h05922d8_5
  - libuv=1.51.0=h2466b09_0
  - libvorbis=1.3.7=h0e60522_0
  - libwebp-base=1.5.0=h3b0e114_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.8=h442d1da_0
  - libzlib=1.3.1=h2466b09_2
  - libzopfli=1.0.3=h0e60522_0
  - llvmlite=0.44.0=py310h0288bfe_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.10.0=h2466b09_1
  - magicgui=0.10.1=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py310h38315fa_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.1=py310hc19bc0b_0
  - napari=0.6.1=pyhd8ed1ab_0
  - napari-base=0.6.1=pyh9208f05_0
  - napari-console=0.1.3=pyh73487a3_0
  - napari-plugin-engine=0.2.0=pyha07c04f_3
  - napari-plugin-manager=0.1.6=pyha07c04f_0
  - napari-svg=0.2.1=pyha07c04f_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - npe2=0.7.8=pyhd8ed1ab_0
  - numba=0.61.2=py310h9216ec7_1
  - numcodecs=0.13.1=py310hb4db72f_0
  - numpydoc=1.8.0=pyhd8ed1ab_1
  - openjpeg=2.5.3=h4d64b90_0
  - openssl=3.5.0=ha4e3fda_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.0=py310hb4db72f_0
  - parso=0.8.4=pyhd8ed1ab_1
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.45=h99c9b8b_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.2.1=py310h9595edc_0
  - pint=0.24.4=pyhd8ed1ab_1
  - pip=25.1.1=pyh8b19718_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.8=pyhe01879c_0
  - ply=3.11=pyhd8ed1ab_3
  - pooch=1.8.2=pyhd8ed1ab_1
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py310ha8f682b_0
  - psygnal=0.13.0=pyhd8ed1ab_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyconify=0.2.1=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.7=pyh3cfb1c2_0
  - pydantic-compat=0.1.2=pyhd8ed1ab_0
  - pydantic-core=2.33.2=py310hed05c55_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyopengl=3.1.9=pyhd8ed1ab_0
  - pyproject_hooks=1.2.0=pyhd8ed1ab_1
  - pyqt=5.15.11=py310h936fe8c_1
  - pyqt5-sip=12.17.0=py310h9e98ed7_1
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.10.18=h8c5b53a_0_cpython
  - python-build=1.2.2.post1=pyhff2d567_1
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-dotenv=1.1.0=pyh29332c3_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=7_cp310
  - pytorch=2.3.1=py3.10_cuda11.8_cudnn8_0
  - pytorch-cuda=11.8=h24eeafa_6
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pywavelets=1.8.0=py310hb0944cc_0
  - pywin32=307=py310h9e98ed7_3
  - pyyaml=6.0.2=py310h38315fa_2
  - pyzmq=27.0.0=py310h656833d_0
  - qt-main=5.15.15=h9151539_4
  - qtconsole-base=5.6.1=pyha770c72_2
  - qtpy=2.4.3=pyhd8ed1ab_1
  - rav1e=0.7.1=ha073cba_3
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.4=pyhd8ed1ab_0
  - rich=14.0.0=pyh29332c3_0
  - rpds-py=0.25.1=py310hed05c55_0
  - scikit-image=0.25.2=py310hb4db72f_1
  - scipy=1.15.2=py310h15c175c_0
  - setuptools=80.9.0=pyhff2d567_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - sip=6.10.0=py310h9e98ed7_0
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h500f7fa_1
  - snowballstemmer=3.0.1=pyhd8ed1ab_0
  - sphinx=8.1.3=pyhd8ed1ab_1
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - superqt=0.7.5=pyhb6d5dde_0
  - svt-av1=3.0.2=he0c23c2_0
  - sympy=1.14.0=pyh04b8f61_5
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tk=8.6.13=h2c6b04d_2
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - tomli-w=1.2.0=pyhd8ed1ab_0
  - toolz=1.0.0=pyhd8ed1ab_1
  - tornado=6.5.1=py310ha8f682b_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typer-slim=0.16.0=pyhe01879c_0
  - typer-slim-standard=0.16.0=hf964461_0
  - typing-extensions=4.14.0=h32cad80_0
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.14.0=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.22621.0=h57928b3_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h41ae7f8_26
  - vc14_runtime=14.44.35208=h818238b_26
  - vispy=0.15.2=py310hb0944cc_0
  - vs2015_runtime=14.44.35208=h38c0c73_26
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - wrapt=1.17.2=py310ha8f682b_0
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - yaml=0.2.5=h8ffe710_2
  - zarr=2.18.3=pyhd8ed1ab_1
  - zeromq=4.3.5=ha9f60a1_7
  - zfp=1.0.1=he0c23c2_2
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib-ng=2.2.4=hbb528cf_0
  - zstandard=0.23.0=py310ha8f682b_2
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - absl-py==2.3.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.3.2
      - async-timeout==5.0.1
      - bermuda==0.1.4
      - bioimageio-core==0.7.0
      - bioimageio-spec==0.5.3.5
      - careamics==0.0.12
      - careamics-napari==0.0.11
      - careamics-portfolio==0.0.15
      - contourpy==1.3.2
      - cycler==0.12.1
      - distro==1.9.0
      - dnspython==2.7.0
      - email-validator==2.2.0
      - fonttools==4.58.4
      - frozenlist==1.7.0
      - grpcio==1.73.0
      - h5py==3.14.0
      - intel-openmp==2021.4.0
      - lightning-utilities==0.14.3
      - loguru==0.7.3
      - markdown==3.8.2
      - matplotlib==3.10.1
      - mkl==2021.4.0
      - numpy==1.26.4
      - propcache==0.3.2
      - protobuf==5.29.1
      - pydantic-settings==2.9.1
      - pyparsing==3.2.3
      - pyqtgraph==0.13.7
      - pytorch-lightning==2.5.0.post0
      - ruyaml==0.91.0
      - tbb==2021.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tifffile==2025.3.13
      - torchmetrics==1.7.3
      - torchvision==0.18.1
      - triangle==20250106
      - typer==0.15.2
      - werkzeug==3.1.3
      - win32-setctime==1.2.0
      - xarray==2025.1.2
      - yarl==1.20.1
prefix: C:\Users\hubbardp\.conda\envs\napari-careamics
```

**Comment by jdeschamps** [comment]
Hi @hubbardp,

Thanks for the issue! We are a bit thinly spread (especially on the napari front...) until September, but we will look into it asap.

It seems to me that it may only be a matter of wrong variable type, which would be easy to fix.

**Comment by jdeschamps** [comment]
Hopefully fixed by https://github.com/CAREamics/careamics-napari/pull/26!

**Comment by jdeschamps** [comment]
Can you try again with the latest version?

**Comment by hubbardp** [comment]
I think I am now getting a different error.

I did:
python -m pip install --upgrade careamics-napari "napari[all]"
And the shell messages end with:
Successfully installed careamics-napari-0.0.12

I trained on one image, then did prediction by choosing a folder with one image and pressing the "Predict" button.  I still get the banner saying "An error occurred during prediction" and in my shell I see the following:

C:/Users/hubbardp/Documents/func-e-worm/careamics-napari-test-01/prediction
06:43:39 : INFO : Thread-13 (_predict) : LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Traceback (most recent call last):
  File "C:\Users\hubbardp\.conda\envs\napari-careamics\lib\site-packages\careamics_napari\workers\prediction_worker.py", line 157, in _predict
    result = careamist.predict(  # type: ignore
  File "C:\Users\hubbardp\.conda\envs\napari-careamics\lib\site-packages\careamics\careamist.py", line 696, in predict
    predictions = self.trainer.predict(
  File "C:\Users\hubbardp\.conda\envs\napari-careamics\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 859, in predict
    return call._call_and_handle_interrupt(
  File "C:\Users\hubbardp\.conda\envs\napari-careamics\lib\site-packages\pytorch_lightning\trainer\call.py", line 47, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\hubbardp\.conda\envs\napari-careamics\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 898, in _predict_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "C:\Users\hubbardp\.conda\envs\napari-careamics\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 982, in _run
    results = self._run_stage()
  File "C:\Users\hubbardp\.conda\envs\napari-careamics\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1021, in _run_stage
    return self.predict_loop.run()
  File "C:\Users\hubbardp\.conda\envs\napari-careamics\lib\site-packages\pytorch_lightning\loops\utilities.py", line 179, in _decorator
    return loop_run(self, *args, **kwargs)
  File "C:\Users\hubbardp\.conda\envs\napari-careamics\lib\site-packages\pytorch_lightning\loops\prediction_loop.py", line 109, in run
    self.on_run_start()
  File "C:\Users\hubbardp\.conda\envs\napari-careamics\lib\site-packages\pytorch_lightning\loops\prediction_loop.py", line 198, in on_run_start
    self._on_predict_start()
  File "C:\Users\hubbardp\.conda\envs\napari-careamics\lib\site-packages\pytorch_lightning\loops\prediction_loop.py", line 344, in _on_predict_start
    call._call_callback_hooks(trainer, "on_predict_start")
  File "C:\Users\hubbardp\.conda\envs\napari-careamics\lib\site-packages\pytorch_lightning\trainer\call.py", line 222, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "C:\Users\hubbardp\.conda\envs\napari-careamics\lib\site-packages\careamics_napari\careamics_utils\callback.py", line 164, in on_predict_start
    if n_batches == np.inf:
NameError: name 'np' is not defined
Error: name 'np' is not defined
ERROR: An error occurred during prediction:
 name 'np' is not defined
Note: if you get an error due to the sizes of Tensors, try using tiling.

**Comment by jdeschamps** [comment]
Thanks to @mese79 , a new version should now be available!
